### ISSUE TITLE
UI displays incorrectly on mobile devices

### ISSUE THREAD

**Issue by grimfand** [R0b0To/iGPan#4]
When I open the application on my mobile device, the UI does not display correctly. Some elements are misaligned and parts of the interface are difficult to interact with.![Screenshot_20250928_091529.jpg](https://github.com/user-attachments/assets/2674fc69-535a-40b4-8c56-cf8802bb3a98)

**Comment by R0b0To** [comment]
Can you tell me the resolution or the name of the device you are using?
The information density is very high and I find difficult to compress more without making everything too small. I'll try to think something but I'm not working on this project right now

**Comment by grimfand** [comment]
I’m using a Samsung Galaxy S20 FE with a resolution of 2400 × 1080.
Thanks for looking into this! I understand you’re not actively working on the project right now, but I appreciate any ideas or suggestions when you get a chance.

**Comment by R0b0To** [comment]
For now, I adjusted the sizes of a few elements.
In the future, I'm thinking to make all container pages scrollable, similar to the staff and reports pages. That should fix the edge cases.

**Comment by grimfand** [comment]
I updated to the latest version, but the issue is still there on my device.
I’ll wait for the upcoming container pages scrollable update — that should hopefully fix it.
